name: Build-Samples
on: workflow_dispatch

jobs:
  build-linux:
    name: Build Samples for Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install cmake clang ninja-build libgl1-mesa-dev libasound2-dev -y --no-install-recommends 
      - name: Build
        run: mkdir -p build; mkdir -p build/linux; cd build/linux; cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../.. && cmake --build . --config release --target install 
      - name: Compress Samples
        run: cd build/linux/Release && zip -r -9 RavEngine_Samples_Linux64.zip *.AppImage
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name:  RavEngine_Samples_linux64
          path:  build/linux/Release/RavEngine_Samples_Linux64.zip

  build-mac:
    name: Build Samples for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir -p build; cd build; cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --config release --target install
      - name: Compress Samples
        run: cd build/release && zip -r -9 RavEngine_Samples_macOS.zip *.app
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_macOS
          path: build/release/RavEngine_Samples_macOS.zip
                
  build-windows:
    name: Build samples for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir build; cd build; mkdir win; cd win; cmake -DCMAKE_BUILD_TYPE=Release ..\.. ; cmake ..\.. ; cmake --build . --config release --target install
      - name: Compress Samples
        run: cd build\win\Release ; Compress-Archive -Path .\RavEngine*.exe,.\RavEngine*.zip -DestinationPath RavEngine_Samples_win64.zip
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_win64
          path: build\win\release\RavEngine_Samples_win64.zip

  build-uwp:
    name: Build samples for UWP
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake Configure
        run: mkdir build; cd build; mkdir uwp; cd uwp; cmake -G "Visual Studio 16 2019" -Ax64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_BUILD_TYPE=Release -Wno-dev ..\.. ; cmake -G "Visual Studio 16 2019" -Ax64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_BUILD_TYPE=Release -Wno-dev ..\..;
      - name: Build & Publish
        run: cd build\uwp ; "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSbuild.exe" "RavEngine_Samples.sln" /p:Configuration=Release;AppxBundle=Always;AppxBundlePlatforms="x64"
      - name: Compress Samples
        run: cd build\uwp; Compress-Archive -Path .\AppPackages -DestinationPath RavEngine_Samples_uwp64.zip
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_win64
          path: build\uwp\RavEngine_Samples_uwp64.zip
