name: Build-Samples
on: push

jobs:
  build-linux:
    name: Build Samples for Linux x64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install cmake g++ ninja-build libgl1-mesa-dev libasound2-dev -y --no-install-recommends 
      - name: Build
        run: mkdir -p build; mkdir -p build/linux; cd build/linux; cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../.. && cmake --build . --config release --target install 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name:  RavEngine_Samples_linux64
          path:  build/linux/Release/*.AppImage

  build-mac:
    name: Build Samples for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir -p build; cd build; cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --config release --target install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_macOS
          path: build/release/*.app
                
  build-windows:
    name: Build samples for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir build; cd build; mkdir win; cd win; cmake -DCMAKE_BUILD_TYPE=Release ..\.. ; cmake ..\.. ; cmake --build . --config release --target install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_win64
          path: |
                build\win\release\RavEngine*.exe 
                build\win\release\RavEngine*.zip 

  build-uwp:
    name: Build samples for UWP
    runs-on: windows-latest
    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake Configure
        run: mkdir build; cd build; mkdir uwp; cd uwp; cmake -G "Visual Studio 16 2019" -Ax64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_BUILD_TYPE=Release -Wno-dev ..\.. ; cmake -G "Visual Studio 16 2019" -Ax64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_BUILD_TYPE=Release -Wno-dev ..\..;
      - name: Build & Publish
        run: cd build\uwp ; & "MSbuild.exe" "RavEngine_Samples.sln" /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="x64"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_uwp64
          path: build\uwp\AppPackages
