name: Build-Samples
on: workflow_dispatch

jobs:
  build-linux:
    name: Build Samples for Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install cmake clang ninja-build libgl1-mesa-dev libasound2-dev -y --no-install-recommends 
      - name: Build
        run: mkdir -p build; mkdir -p build/linux; cd build/linux; cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../.. && cmake --build . --config release --target install 
      - name: Compress Samples
        run: cd build/linux/Release && zip -r -9 RavEngine_Samples_Linux64.zip *.AppImage
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name:  RavEngine_Samples_linux64
          path:  build/linux/Release/RavEngine_Samples_Linux64.zip

  build-mac:
    name: Build Samples for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir -p build; cd build; cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --config release --target install
      - name: Compress Samples
        run: cd build/release && zip -r -9 RavEngine_Samples_macOS.zip *.app
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_macOS
          path: build/release/RavEngine_Samples_macOS.zip
                
  build-windows:
    name: Build samples for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release .. ; cmake .. ; cmake --build . --config release --target install
      - name: Compress Samples
        run: cd build\Release ; Compress-Archive -Path .\RavEngine*.exe,.\RavEngine*.zip -DestinationPath RavEngine_Samples_win64.zip
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RavEngine_Samples_win64
          path: build\release\RavEngine_Samples_win64.zip
