name: Build-Samples
on: workflow_dispatch

jobs:
  build-linux:
    name: Build Samples for Linux x64
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo apt-get install cmake clang ninja-build -y --no-install-recommends 
      - name: Build
        run: ./build-linux.sh
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: build/Release/
                !build/Release/bin    

  build-mac:
    name: Build Samples for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: ./build-mac.sh
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: build/release/
                !build/release/bin
        
  build-windows:
    name: Build samples for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: .\build-win.bat    
      - name: Build For Real
        run: .\build-win.bat
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: build/release/
                !build/release/bin    
